# Generated by Django 5.1.1 on 2024-09-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approval', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Approval_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Approval.approval_user')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
