# Generated by Django 5.1.1 on 2024-09-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approval', '0003_remove_productscart_product_productscart_product'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscart',
            name='Product',
        ),
        migrations.AddField(
            model_name='productscart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
