# Generated by Django 5.1.1 on 2024-09-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Approval', '0004_remove_productscart_product_productscart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscart',
            old_name='quantity',
            new_name='cart_quantity',
        ),
    ]
