# Generated by Django 5.1.1 on 2024-09-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Approval', '0005_rename_quantity_productscart_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscart',
            old_name='Approval_user',
            new_name='Approval_user_id',
        ),
        migrations.RenameField(
            model_name='productscart',
            old_name='product',
            new_name='product_id',
        ),
    ]
