# Generated by Django 5.1.1 on 2024-09-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Approval', '0006_rename_approval_user_productscart_approval_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscart',
            old_name='Approval_user_id',
            new_name='Approval_user',
        ),
        migrations.RenameField(
            model_name='productscart',
            old_name='product_id',
            new_name='product',
        ),
    ]
